### PR TITLE
Integrated JSHint for static analysis

### PR DESCRIPTION
**Pull request by Abdulaziz57**
## Summary
This PR integrates JSHint into the project for static analysis of the JavaScript codebase. JSHint helps in identifying potential errors and enforces coding standards by analyzing code for syntax issues, potential bugs, and stylistic problems.

## Changes
- Created a JSHint configuration file (`.jshintrc`) to specify linting rules for the project.
- Ran JSHint on the codebase to identify and correct any errors or warnings.

## Evidence of Installation and Execution

1. **Installation of JSHint**:
This screenshot shows the successful installation of JSHint using npm install jshint --save-dev. 
   Screenshot 2024-10-23 at 2 22 25 PM

2. **Configuration of JSHint**:
This shows the configuration in .jshintrc. 
   Screenshot 2024-10-23 at 2 31 19 PM

3. **Running JSHint**:
The following image displays the results from running JSHint on a specific directory within the codebase. Due to space constraints, I have only shown a partial result rather than the entire codebase analysis.
   Screenshot 2024-10-23 at 2 32 15 PM

### CODE REVIEW

**Comment by Bchenjamin** [comment]
Can you expand on the space constraints?

**Review by Bchenjamin — APPROVED** [review]
LGTM!

**Comment by Abdulaziz57** [comment]
What I meant with space constraints is when I am testing the whole codebase or a large directory such as 'src', I get lots of tests on the terminal, and can't show it in one screenshot.

**Comment by Abdulaziz57** [comment]
This is what shows when I test a large portion of the codebase, the full result cannot be seen (only a small portion of the result).
Screenshot 2024-10-24 at 3 08 53 PM

**Comment by Bchenjamin** [comment]
For Project 3C, I have integrated JSHint to the workflow. 
Details can be found in the Tool Analysis Design Doc on Gradescope.

**Pull request merged**
